### PR TITLE
Render distance key in JSON on `/retailers.json?address=22314`

### PR DESCRIPTION
**Pull request by jwieringa**
This adds the distance key to the JSON response on `/retailers.json?address=22314` and `/retailers/nearaddy.json?address=22314`

### CODE REVIEW

**Comment by jwieringa** [comment]
Noting that I understand that `/retailers/nearaddy.json` needs to be fixed regardless because of a switch because of already installed/deployed iOS applications.

**Comment by jwieringa** [comment]
@abannert I think this pull request should fix the issue in the iOS application.

I had to modify original methods written quite a while back which I've been avoiding in order to reduce the number of regressions in the API. I've browsed manually the JSON, text, and XML endpoints on `/retailers/nearaddy` and have not observed any errors or regressions, but heads up just in case!

Here is what the API is now returning:

screen shot 2016-08-13 at 1 12 08 pm

**Comment by jwieringa** [comment]
Until we get some test harness on the repo, here are the test logs:

```
$ docker-compose -f docker-compose.test.yml up --no-deps snapfresh
Recreating allincomefoods_snapfresh_1
Attaching to allincomefoods_snapfresh_1
snapfresh_1  | allincomefoods_test already exists
snapfresh_1  | Run options: --seed 40750
snapfresh_1  |
snapfresh_1  | # Running:
snapfresh_1  |
snapfresh_1  | ................................
snapfresh_1  |
snapfresh_1  | Finished in 2.772790s, 11.5407 runs/s, 16.5898 assertions/s.
snapfresh_1  |
snapfresh_1  | 32 runs, 46 assertions, 0 failures, 0 errors, 0 skips
snapfresh_1  | Coverage report generated for MiniTest to /opt/app/coverage. 122 / 129 LOC (94.57%) covered.
allincomefoods_snapfresh_1 exited with code 0
```

**Comment by shrtlist** [comment]
@jwieringa did the original `/retailers/nearaddy.json` API return a number or a dictionary for `retailer.distance`?

**Comment by jwieringa** [comment]
Good question, I'm not sure since I didn't capture a test for it before I
started making changes.

I'll check out the older version and find out.

**Comment by abannert** [comment]
Done and deployed. It works now on iOS and SnapFresh.org. Nice work @jwieringa :)

**Comment by shrtlist** [comment]
@abannert I just downloaded SnapFresh for iOS from the App Store, and it's still crashing. Are we sure this is fixed? I think the old API returned a number (in quotes? i.e. "452") for `retailer.distance`, and that's what the app is expecting if I'm not mistaken.

**Comment by shrtlist** [comment]
@abannert @jwieringa given the ongoing impact to iOS app users, I removed the app from sale for now. Any thoughts as to next steps?

**Pull request merged**
