### PR TITLE
Rails Upgrade and Refactor

### PR DESCRIPTION
**Pull request by jwieringa**

### CODE REVIEW

**Comment by shrtlist** [comment]
Hey Jason, is it safe to merge this pull request?

**Comment by jwieringa** [comment]
@shrtlist Hello, sorry for the delay! I completely missed you messaged.

This is not yet safe to merge, the endpoint that generates the text for SMS messages requires looking at. The methods used for generating that were removed from the current version of Rails which is not a problem, but needs a little work.

I've signed up to guide folks through working on this project at Rubyforgood.org. i.e. now I am publicly committed to finishing it. :smile: Thus, this pull request (2 years!!?) should be wrapped up in July.

Thank you for the patience.

**Comment by shrtlist** [comment]
@jwieringa, great to hear!

**Comment by jwieringa** [comment]
This PR is nearing completion and is on the latest Rails version.

Next I'll be testing running under production environment and once that passes this will be good to merge.

**Comment by jwieringa** [comment]
This has lingered for a long time and I'm sorry. If there is still interest in merging, this PR is ready. A few notable items:

+ Disabled retailer types: There seems to be something wrong with the Yelp integration at the moment, so I turned it off for the time being https://github.com/SnapFresh/SnapFresh/pull/44/commits/bb521d920de398529eb233b57f96ba6306d5ac5d
+ Production "like" testing: Added a Docker container with docker-compose which is an effort to test the application similar to the server where the application is hosted (Ruby 1.9, Ubuntu 14.04, Passenger + Apache2)

**Comment by jwieringa** [comment]
Thanks!

**Pull request merged**
